<?php
/**
 * Language labels for database tables/fields belonging to extension "timtab"
 *
 * This file is detected by the translation tool.
 * 
 * $Id$
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'tt_news.tx_timtab_trackbacks' => 'Trackbacks',
		'tt_news.tx_timtab_ping_allowed' => 'Allow Pings',
		'tt_news.tx_timtab_comments_allowed' => 'Allow Comments',
		'tt_news.type.I.timtab' => 'Blog Post',
		'tx_timtab_blogroll' => 'Link',
		'tx_timtab_blogroll.url' => 'URL',
		'tx_timtab_blogroll.name' => 'link name',
		'tx_timtab_blogroll.description' => 'short description',
		'tx_timtab_blogroll.rel_identity' => 'identity',
		'tx_timtab_blogroll.rel_identity.I.0' => 'another web address of mine',
		'tx_timtab_blogroll.rel_friendship' => 'friendship',
		'tx_timtab_blogroll.rel_friendship.I.0' => 'none',
		'tx_timtab_blogroll.rel_friendship.I.1' => 'acquaintance',
		'tx_timtab_blogroll.rel_friendship.I.2' => 'contact',
		'tx_timtab_blogroll.rel_friendship.I.3' => 'friend',
		'tx_timtab_blogroll.rel_physical' => 'physical',
		'tx_timtab_blogroll.rel_physical.I.0' => 'met',
		'tx_timtab_blogroll.rel_professional' => 'professional',
		'tx_timtab_blogroll.rel_professional.I.0' => 'co-worker',
		'tx_timtab_blogroll.rel_professional.I.1' => 'colleague',
		'tx_timtab_blogroll.rel_geographical.I.0' => 'none',
		'tx_timtab_blogroll.rel_geographical.I.1' => 'co-resident',
		'tx_timtab_blogroll.rel_geographical.I.2' => 'neighbor',
		'tx_timtab_blogroll.rel_geographical' => 'geographical',
		'tx_timtab_blogroll.rel_family' => 'family',
		'tx_timtab_blogroll.rel_family.I.0' => 'none',
		'tx_timtab_blogroll.rel_family.I.1' => 'child',
		'tx_timtab_blogroll.rel_family.I.2' => 'kin',
		'tx_timtab_blogroll.rel_family.I.3' => 'parent',
		'tx_timtab_blogroll.rel_family.I.4' => 'sibling',
		'tx_timtab_blogroll.rel_family.I.5' => 'spouse',
		'tx_timtab_blogroll.rel_romantic' => 'romantic',
		'tx_timtab_blogroll.rel_romantic.I.0' => 'muse',
		'tx_timtab_blogroll.rel_romantic.I.1' => 'crush',
		'tx_timtab_blogroll.rel_romantic.I.2' => 'date',
		'tx_timtab_blogroll.rel_romantic.I.3' => 'sweetheart',
		'tx_timtab_blogroll.img_uri' => 'image URL',
		'tx_timtab_blogroll.rss_uri' => 'RSS URL',
		'tx_timtab_blogroll.notes' => 'notes',
		'tx_timtab_blogroll.rating' => 'rating',
		'tx_timtab_blogroll.rating.I.0' => '0',
		'tx_timtab_blogroll.rating.I.1' => '1',
		'tx_timtab_blogroll.rating.I.2' => '2',
		'tx_timtab_blogroll.rating.I.3' => '3',
		'tx_timtab_blogroll.rating.I.4' => '4',
		'tx_timtab_blogroll.rating.I.5' => '5',
		'tx_timtab_blogroll.rating.I.6' => '6',
		'tx_timtab_blogroll.rating.I.7' => '7',
		'tx_timtab_blogroll.rating.I.8' => '8',
		'tx_timtab_blogroll.rating.I.9' => '9',
		'tx_timtab_blogroll.target' => 'link target',
		'tx_timtab_blogroll.target.I.0' => 'none (Note that the target attribute is illegal in XHTML 1.1 and 1.0 Strict.)',
		'tx_timtab_blogroll.target.I.1' => '_blank',
		'tx_timtab_blogroll.target.I.2' => '_top',
		'tt_content.list_type_pi1' => 'blogroll',
	),
	'dk' => Array (
	),
	'de' => Array (
		'tt_news.tx_timtab_trackbacks' => 'Trackbacks',
		'tt_news.tx_timtab_ping_allowed' => 'Erlaube Pings',
		'tt_news.tx_timtab_comments_allowed' => 'Erlaube Comments',
		'tt_news.type.I.timtab' => 'Blog Post',
		'tx_timtab_blogroll' => 'Link',
		'tx_timtab_blogroll.url' => 'URL',
		'tx_timtab_blogroll.name' => 'Link Name',
		'tx_timtab_blogroll.description' => 'Kurze Beschreibung',
		'tx_timtab_blogroll.rel_identity' => 'Identität',
		'tx_timtab_blogroll.rel_identity.I.0' => 'Eine weitere Website von mir',
		'tx_timtab_blogroll.rel_friendship' => 'Freundschaft',
		'tx_timtab_blogroll.rel_friendship.I.0' => '-',
		'tx_timtab_blogroll.rel_friendship.I.1' => 'Bekanntschaft',
		'tx_timtab_blogroll.rel_friendship.I.2' => 'Kontakt',
		'tx_timtab_blogroll.rel_friendship.I.3' => 'Freund',
		'tx_timtab_blogroll.rel_physical' => 'Körperlich',
		'tx_timtab_blogroll.rel_physical.I.0' => 'getroffen',
		'tx_timtab_blogroll.rel_professional' => 'Beruflich',
		'tx_timtab_blogroll.rel_professional.I.0' => 'Arbeitskollege',
		'tx_timtab_blogroll.rel_professional.I.1' => '(Fach)Kollege',
		'tx_timtab_blogroll.rel_geographical.I.0' => '-',
		'tx_timtab_blogroll.rel_geographical.I.1' => 'Mitbewohner',
		'tx_timtab_blogroll.rel_geographical.I.2' => 'Nachbar',
		'tx_timtab_blogroll.rel_geographical' => 'Regional',
		'tx_timtab_blogroll.rel_family' => 'Familie',
		'tx_timtab_blogroll.rel_family.I.0' => '-',
		'tx_timtab_blogroll.rel_family.I.1' => 'Kind',
		'tx_timtab_blogroll.rel_family.I.2' => 'Verwandter',
		'tx_timtab_blogroll.rel_family.I.3' => 'Elternteil',
		'tx_timtab_blogroll.rel_family.I.4' => 'Bruder/Schwester',
		'tx_timtab_blogroll.rel_family.I.5' => 'Ehepartner',
		'tx_timtab_blogroll.rel_romantic' => 'Romantisch',
		'tx_timtab_blogroll.rel_romantic.I.0' => 'Muse',
		'tx_timtab_blogroll.rel_romantic.I.1' => 'verliebt',
		'tx_timtab_blogroll.rel_romantic.I.2' => 'Date',
		'tx_timtab_blogroll.rel_romantic.I.3' => 'Liebling',
		'tx_timtab_blogroll.img_uri' => 'Bild URL',
		'tx_timtab_blogroll.rss_uri' => 'RSS URL',
		'tx_timtab_blogroll.notes' => 'Notizen',
		'tx_timtab_blogroll.rating' => 'Bewertung',
		'tx_timtab_blogroll.rating.I.0' => '0',
		'tx_timtab_blogroll.rating.I.1' => '1',
		'tx_timtab_blogroll.rating.I.2' => '2',
		'tx_timtab_blogroll.rating.I.3' => '3',
		'tx_timtab_blogroll.rating.I.4' => '4',
		'tx_timtab_blogroll.rating.I.5' => '5',
		'tx_timtab_blogroll.rating.I.6' => '6',
		'tx_timtab_blogroll.rating.I.7' => '7',
		'tx_timtab_blogroll.rating.I.8' => '8',
		'tx_timtab_blogroll.rating.I.9' => '9',
		'tx_timtab_blogroll.target' => 'Link Target',
		'tx_timtab_blogroll.target.I.0' => '- (Beachte das das target Attribut in XHTML 1.1 and 1.0 Strict nicht erlaubt ist.)',
		'tx_timtab_blogroll.target.I.1' => '_blank',
		'tx_timtab_blogroll.target.I.2' => '_top',
		'tt_content.list_type_pi1' => 'Blogroll',
	),
	'no' => Array (
	),
	'it' => Array (
		'tt_news.tx_timtab_trackbacks' => 'Trackbacks',
		'tt_news.tx_timtab_ping_allowed' => 'Permetti Pings',
		'tt_news.tx_timtab_comments_allowed' => 'Permetti Commenti',
		'tt_news.type.I.timtab' => 'Post',
		'tx_timtab_blogroll' => 'Link',
		'tx_timtab_blogroll.url' => 'URL',
		'tx_timtab_blogroll.name' => 'link',
		'tx_timtab_blogroll.description' => 'breve descrizione',
		'tx_timtab_blogroll.rel_identity' => 'identità',
		'tx_timtab_blogroll.rel_identity.I.0' => 'secondo indirizzo web',
		'tx_timtab_blogroll.rel_friendship' => 'amici',
		'tx_timtab_blogroll.rel_friendship.I.0' => 'nessuno',
		'tx_timtab_blogroll.rel_friendship.I.2' => 'contatto',
		'tx_timtab_blogroll.rel_friendship.I.3' => 'amico',
		'tx_timtab_blogroll.rel_physical' => 'fisico',
		'tx_timtab_blogroll.rss_uri' => 'RSS URL',
		'tx_timtab_blogroll.notes' => 'note',
		'tx_timtab_blogroll.rating' => 'voto',
		'tx_timtab_blogroll.rating.I.0' => '0',
		'tx_timtab_blogroll.rating.I.1' => '1',
		'tx_timtab_blogroll.rating.I.2' => '2',
		'tx_timtab_blogroll.rating.I.3' => '3',
		'tx_timtab_blogroll.rating.I.4' => '4',
		'tx_timtab_blogroll.rating.I.5' => '5',
		'tx_timtab_blogroll.rating.I.6' => '6',
		'tx_timtab_blogroll.rating.I.7' => '7',
		'tx_timtab_blogroll.rating.I.8' => '8',
		'tx_timtab_blogroll.rating.I.9' => '9',
		'tx_timtab_blogroll.target' => 'link target',
		'tx_timtab_blogroll.target.I.1' => '_nuova',
		'tx_timtab_blogroll.target.I.2' => '_top',
		'tt_content.list_type_pi1' => 'blogs',
	),
	'fr' => Array (
	),
	'es' => Array (
	),
	'nl' => Array (
		'tt_news.tx_timtab_trackbacks' => 'Trackbacks',
		'tt_news.tx_timtab_ping_allowed' => 'Pings toestaan',
		'tt_news.tx_timtab_comments_allowed' => 'Reacties toestaan',
		'tt_news.type.I.timtab' => 'Blog Post',
		'tx_timtab_blogroll' => 'Link',
		'tx_timtab_blogroll.url' => 'URL',
		'tx_timtab_blogroll.name' => 'naam voor de link',
		'tx_timtab_blogroll.description' => 'korte omschrijving',
		'tx_timtab_blogroll.rel_identity' => 'identiteit',
		'tx_timtab_blogroll.rel_identity.I.0' => 'een van mijn andere webadressen',
		'tx_timtab_blogroll.rel_friendship' => 'vriendschap',
		'tx_timtab_blogroll.rel_friendship.I.0' => 'geen',
		'tx_timtab_blogroll.rel_friendship.I.1' => 'kennis',
		'tx_timtab_blogroll.rel_friendship.I.2' => 'contact',
		'tx_timtab_blogroll.rel_friendship.I.3' => 'vriend',
		'tx_timtab_blogroll.rel_physical' => 'fysiek',
		'tx_timtab_blogroll.rel_physical.I.0' => 'ontmoet',
		'tx_timtab_blogroll.rel_professional' => 'professional',
		'tx_timtab_blogroll.rel_professional.I.0' => 'medewerker',
		'tx_timtab_blogroll.rel_professional.I.1' => 'collega',
		'tx_timtab_blogroll.rel_geographical.I.0' => 'geen',
		'tx_timtab_blogroll.rel_geographical.I.1' => 'mede-ingezetene',
		'tx_timtab_blogroll.rel_geographical.I.2' => 'buurman',
		'tx_timtab_blogroll.rel_geographical' => 'geografisch',
		'tx_timtab_blogroll.rel_family' => 'familie',
		'tx_timtab_blogroll.rel_family.I.0' => 'geen',
		'tx_timtab_blogroll.rel_family.I.1' => 'kind',
		'tx_timtab_blogroll.rel_family.I.2' => 'verwanten',
		'tx_timtab_blogroll.rel_family.I.3' => 'ouder',
		'tx_timtab_blogroll.rel_family.I.4' => 'nakomeling',
		'tx_timtab_blogroll.rel_family.I.5' => 'echtgenoot',
		'tx_timtab_blogroll.rel_romantic' => 'romantisch',
		'tx_timtab_blogroll.rel_romantic.I.0' => 'muse',
		'tx_timtab_blogroll.rel_romantic.I.1' => 'verkikkerd',
		'tx_timtab_blogroll.rel_romantic.I.2' => 'afspraakje',
		'tx_timtab_blogroll.rel_romantic.I.3' => 'liefje',
		'tx_timtab_blogroll.img_uri' => 'URL afbeelding',
		'tx_timtab_blogroll.rss_uri' => 'URL RSS',
		'tx_timtab_blogroll.notes' => 'aantekeningen',
		'tx_timtab_blogroll.rating' => 'waardering',
		'tx_timtab_blogroll.rating.I.0' => '0',
		'tx_timtab_blogroll.rating.I.1' => '1',
		'tx_timtab_blogroll.rating.I.2' => '2',
		'tx_timtab_blogroll.rating.I.3' => '3',
		'tx_timtab_blogroll.rating.I.4' => '4',
		'tx_timtab_blogroll.rating.I.5' => '5',
		'tx_timtab_blogroll.rating.I.6' => '6',
		'tx_timtab_blogroll.rating.I.7' => '7',
		'tx_timtab_blogroll.rating.I.8' => '8',
		'tx_timtab_blogroll.rating.I.9' => '9',
		'tx_timtab_blogroll.target' => 'link target',
		'tx_timtab_blogroll.target.I.0' => 'geen (Hou er rekening mee dat het target attribuut niet meer geldig is in XHTML 1.1 and 1.0 Strict.)',
		'tx_timtab_blogroll.target.I.1' => '_blank',
		'tx_timtab_blogroll.target.I.2' => '_top',
		'tt_content.list_type_pi1' => 'blogroll',
	),
	'cz' => Array (
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
	'eo' => Array (
	),
	'my' => Array (
	),
	'hi' => Array (
	),
);
?>